# Generated by Django 3.1.3 on 2023-06-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlimentProduct', '0002_remove_alimentos_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('catadores', models.PositiveSmallIntegerField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Alimentos',
        ),
    ]
